version: 2
updates:
- package-ecosystem: nuget
  directory: "/tools/OpenAPIParser"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/tools/MetadataParser"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
